# app/services/ai_privacy_tokenizer.py
"""
Privacy & Data Minimization Tokenizer for 4-Level Treasury AI Architecture

Responsibilities:
1. Sanitizes sensitive company/beneficiary strings & LG numbers in USER QUESTIONS before external transmission.
2. Minimizes & tokenizes internal DB records for Level 2 multi-step LLM synthesis (e.g. LG_TOKEN_001, BENEFICIARY_TOKEN_001).
3. Validates AI Output: Detects all tokens in LLM response and REJECTS any token not generated by the application.
4. Detokenizes valid tokens back to customer values post-validation.
"""

import re
import logging
from typing import Dict, Any, List, Tuple, Set

logger = logging.getLogger(__name__)

# Sensitive identifier patterns
LG_NUMBER_PATTERN = re.compile(r'\b(?:LG|ACME|NBE|HSBC|BM|CIB|ADIB|QNB|SCB|CITI|DB)[-/A-Z0-9]{3,20}\b', re.IGNORECASE)


class PrivacyTokenizer:
    """
    Application Data Minimization & Confidentiality Layer.
    Keeps token mapping internal. Never exposes mapping to external AI.
    """

    def sanitize_user_question(self, question: str) -> Tuple[str, Dict[str, str]]:
        """
        Tokenizes sensitive LG numbers and company identifiers in the user's question.
        Returns: (sanitized_question, token_mapping)
        """
        token_map = {}
        reverse_map = {}

        def replace_lg(match):
            original = match.group(0)
            if original not in token_map:
                token = f"LG_TOKEN_{len(token_map) + 1:03d}"
                token_map[original] = token
                reverse_map[token] = original
            return token_map[original]

        sanitized = LG_NUMBER_PATTERN.sub(replace_lg, question)
        return sanitized, reverse_map

    def tokenize_dataset(self, records: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], Dict[str, str]]:
        """
        Tokenizes database records for Level 2 LLM synthesis.
        """
        tokenized_list = []
        token_to_value = {}
        lg_counter = 1
        ben_counter = 1
        bank_counter = 1

        beneficiary_map = {}
        bank_map = {}

        for rec in records:
            orig_lg = rec.get("lg_number", "LG-000")
            orig_ben = rec.get("beneficiary", "Corporate")
            orig_bank = rec.get("issuing_bank", "Bank")

            lg_token = f"LG_TOKEN_{lg_counter:03d}"
            lg_counter += 1
            token_to_value[lg_token] = orig_lg

            if orig_ben not in beneficiary_map:
                ben_token = f"BENEFICIARY_TOKEN_{ben_counter:03d}"
                ben_counter += 1
                beneficiary_map[orig_ben] = ben_token
                token_to_value[ben_token] = orig_ben
            else:
                ben_token = beneficiary_map[orig_ben]

            if orig_bank not in bank_map:
                bank_token = f"BANK_TOKEN_{bank_counter:03d}"
                bank_counter += 1
                bank_map[orig_bank] = bank_token
                token_to_value[bank_token] = orig_bank
            else:
                bank_token = bank_map[orig_bank]

            tokenized_rec = dict(rec)
            tokenized_rec["lg_number"] = lg_token
            tokenized_rec["beneficiary"] = ben_token
            tokenized_rec["issuing_bank"] = bank_token
            tokenized_list.append(tokenized_rec)

        return tokenized_list, token_to_value

    def tokenize_complex_payload(
        self,
        records: List[Dict[str, Any]],
        beneficiary_summary: Dict[str, Any],
        facility_summary: List[Dict[str, Any]]
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any], List[Dict[str, Any]], Dict[str, str]]:
        """
        Tokenizes raw records, pre-calculated beneficiary aggregates, and facility headroom
        using a unified token registry for Level 2 analysis.
        """
        tokenized_records, valid_tokens = self.tokenize_dataset(records)

        # Reverse map for quick lookup: original_name -> token
        val_to_token = {v: k for k, v in valid_tokens.items()}

        # Tokenize pre-calculated beneficiary summary
        tokenized_bens = {}
        for ben_name, data in beneficiary_summary.items():
            ben_token = val_to_token.get(ben_name)
            if not ben_token:
                ben_token = f"BENEFICIARY_TOKEN_{len(valid_tokens) + 1:03d}"
                valid_tokens[ben_token] = ben_name
                val_to_token[ben_name] = ben_token

            tok_data = dict(data)
            # Tokenize any LGs inside expiring_in_90_days
            if "expiring_in_90_days" in tok_data:
                tok_exp = []
                for exp_item in tok_data["expiring_in_90_days"]:
                    tok_item = dict(exp_item)
                    orig_lg = exp_item.get("lg_number")
                    if orig_lg in val_to_token:
                        tok_item["lg_number"] = val_to_token[orig_lg]
                    tok_exp.append(tok_item)
                tok_data["expiring_in_90_days"] = tok_exp

            tokenized_bens[ben_token] = tok_data

        # Tokenize pre-calculated facility summary
        tokenized_facs = []
        for fac in facility_summary:
            tok_fac = dict(fac)
            orig_b = fac.get("bank")
            if orig_b:
                if orig_b not in val_to_token:
                    bank_tok = f"BANK_TOKEN_{len(valid_tokens) + 1:03d}"
                    valid_tokens[bank_tok] = orig_b
                    val_to_token[orig_b] = bank_tok
                else:
                    bank_tok = val_to_token[orig_b]
                tok_fac["bank"] = bank_tok
            tokenized_facs.append(tok_fac)

        return tokenized_records, tokenized_bens, tokenized_facs, valid_tokens

    def validate_ai_output_tokens(self, response_text: str, valid_tokens: Dict[str, str]) -> Tuple[bool, str]:
        """
        Inspects LLM output for tokens.
        REJECTS response if AI returns any token NOT present in valid_tokens mapping.
        """
        found_tokens = re.findall(r'\b(?:LG_TOKEN|BENEFICIARY_TOKEN|BANK_TOKEN)_\d{3}\b', response_text)
        
        for token in found_tokens:
            if token not in valid_tokens:
                logger.error(f"Security Alert: AI returned unrecognized/hallucinated token: {token}")
                return False, f"Output validation failed: AI returned unrecognized token '{token}'."

        return True, "Output Validation Passed"

    def detokenize_response(self, response_text: str, valid_tokens: Dict[str, str]) -> str:
        """
        Replaces tokens with original customer values post-validation.
        """
        detokenized = response_text
        for token, original in valid_tokens.items():
            detokenized = detokenized.replace(token, str(original))
        return detokenized


privacy_tokenizer = PrivacyTokenizer()
