# app/services/inbox_outbound_service.py
"""
Outbound Email Service for Smart Inbox
Handles sending data request emails (e.g. Monthly LG Position Requests) to banks.
Attaches custom Message-ID headers for robust thread matching upon bank reply.
"""

import os
import smtplib
import email
import email.utils
import logging
from datetime import datetime, date, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional, Dict, Any, Tuple

from sqlalchemy.orm import Session

from app.models.models import Bank, Customer
from app.models.models_quotation import QuotationBank
from app.models.models_inbox import InboxOutboundRequest, InboxScheduleConfig
from app.core.email_service import get_customer_email_settings, process_recipients

logger = logging.getLogger("app.inbox_outbound")


class InboxOutboundService:
    """
    Manages sending system-initiated data request emails to banks.
    """

    def _compose_lg_position_email(
        self,
        customer_name: str,
        bank_name: str,
        position_date: date,
        request_reference: str,
        custom_notes: Optional[str] = None
    ) -> Tuple[str, str]:
        """Generates subject and bilingual HTML body for LG position request with unique reference number."""
        date_str = position_date.strftime("%d/%m/%Y")
        subject = f"[Ref: {request_reference}] [LG Position Request] {customer_name} — Position as of {date_str}"

        notes_html = f"<p style='margin-top:10px; color:#4b5563;'><strong>Notes:</strong> {custom_notes}</p>" if custom_notes else ""

        html_body = f"""
        <!DOCTYPE html>
        <html dir="ltr" lang="en">
        <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1f2937; margin: 0; padding: 20px; }}
                .card {{ max-width: 600px; margin: auto; background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 24px; }}
                .header {{ border-bottom: 2px solid #3b82f6; padding-bottom: 12px; margin-bottom: 16px; }}
                .header h2 {{ margin: 0; color: #1e3a8a; font-size: 20px; }}
                .highlight {{ background: #eff6ff; border-left: 4px solid #3b82f6; padding: 12px; border-radius: 4px; margin: 16px 0; }}
                .ar {{ direction: rtl; text-align: right; margin-top: 24px; border-top: 1px dashed #d1d5db; padding-top: 16px; }}
                .footer {{ margin-top: 24px; font-size: 12px; color: #6b7280; border-top: 1px solid #f3f4f6; padding-top: 12px; }}
            </style>
        </head>
        <body>
            <div class="card">
                <div class="header">
                    <h2>Letter of Guarantee Position Request</h2>
                </div>
                <p>Dear <strong>{bank_name}</strong> Corporate Treasury & Trade Finance Team,</p>
                <p>On behalf of <strong>{customer_name}</strong>, we kindly request the official Letter of Guarantee (LG) position report representing all active guarantees issued through your esteemed bank as of the following snapshot date:</p>
                
                <div class="highlight">
                    <p style="margin:0;"><strong>Reference No. / الرقم المرجعي:</strong> <span style="font-family: monospace; font-size: 15px; font-weight: bold; color: #1e3a8a;">{request_reference}</span></p>
                    <p style="margin:4px 0 0 0;"><strong>Company:</strong> {customer_name}</p>
                    <p style="margin:4px 0 0 0;"><strong>Requested Position Date:</strong> {date_str}</p>
                </div>

                <p>Please reply directly to this email with the position report in Excel (preferred) or PDF format.</p>
                <p style="font-size: 13px; color: #4b5563;"><em>Note: If there are no active guarantees under our entity as of this date, kindly reply stating "NIL / Zero Position".</em></p>
                {notes_html}

                <div class="ar">
                    <p>السادة / فريق تمويل التجارة والضمانات بـ <strong>{bank_name}</strong>،</p>
                    <p>بالإشارة إلى التسهيلات الائتمانية الخاصة بشركة <strong>{customer_name}</strong>، برجاء التكرم بموافاتنا بموقف خطابات الضمان السارية والصادرة من طرفكم لصالح شركتنا حتى تاريخ <strong>{date_str}</strong>.</p>
                    <p>يرجى التكرم بالرد على هذا البريد الإلكتروني مباشرة وإرفاق بيان الضمانات (Excel / PDF)، أو الإفادة كتابياً في حال عدم وجود خطابات ضمان قائمة (موقف صفر).</p>
                </div>

                <div class="footer">
                    <p>This automated message was generated by Grow Treasury Platform for {customer_name} [Ref: {request_reference}]. Please reply directly to this email.</p>
                </div>
            </div>
        </body>
        </html>
        """
        return subject, html_body

    def send_position_request(
        self,
        db: Session,
        customer_id: int,
        bank_id: int,
        position_date: Optional[date] = None,
        custom_recipients: Optional[List[str]] = None,
        custom_subject: Optional[str] = None,
        custom_notes: Optional[str] = None,
        user_id: Optional[int] = None
    ) -> InboxOutboundRequest:
        """
        Sends an LG position request email to a specific bank and logs the outbound request.
        """
        customer = db.query(Customer).filter(Customer.id == customer_id, Customer.is_deleted == False).first()
        if not customer:
            raise ValueError(f"Customer {customer_id} not found")

        bank = db.query(Bank).filter(Bank.id == bank_id, Bank.is_deleted == False).first()
        if not bank:
            raise ValueError(f"Bank {bank_id} not found")

        pos_date = position_date or date.today()

        # Generate unique human-readable Reference Number
        # e.g. POS-20260825-9A4B
        hash_seed = f"{customer_id}-{bank_id}-{pos_date}-{datetime.now(timezone.utc).isoformat()}".encode()
        suffix = hashlib.md5(hash_seed).hexdigest()[:4].upper()
        req_ref = f"POS-{pos_date.strftime('%Y%m%d')}-{suffix}"

        # Determine recipient emails
        recipients = []
        if custom_recipients:
            recipients = [r.strip() for r in custom_recipients if r.strip()]

        if not recipients:
            # Check QuotationBank configured emails for this bank
            q_bank = db.query(QuotationBank).filter(
                QuotationBank.customer_id == customer_id,
                QuotationBank.bank_id == bank_id,
                QuotationBank.is_deleted == False
            ).first()
            if q_bank and q_bank.emails:
                recipients = q_bank.emails if isinstance(q_bank.emails, list) else [q_bank.emails]

        if not recipients and bank.email_domain:
            recipients = [f"trade-finance@{bank.email_domain}"]

        if not recipients:
            raise ValueError(f"No recipient email addresses found for bank '{bank.name}'. Please specify recipient emails.")

        # Subject & Body
        default_subject, html_body = self._compose_lg_position_email(
            customer_name=customer.name,
            bank_name=bank.name,
            position_date=pos_date,
            request_reference=req_ref,
            custom_notes=custom_notes
        )
        subject = custom_subject or default_subject

        # Get customer email settings
        email_settings, source = get_customer_email_settings(db, customer_id)
        if not email_settings.smtp_host or not email_settings.sender_email:
            raise ValueError(f"Customer {customer_id} does not have valid SMTP settings configured.")

        # Generate unique Message-ID
        timestamp = int(datetime.now(timezone.utc).timestamp())
        msg_id_domain = email_settings.sender_email.split("@")[-1] if "@" in email_settings.sender_email else "grow.com"
        message_id_header = f"req-{customer_id}-{bank_id}-{pos_date.strftime('%Y%m%d')}-{timestamp}@{msg_id_domain}"

        # Construct MIME message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{email_settings.sender_display_name or customer.name} <{email_settings.sender_email}>"
        msg["To"] = ", ".join(recipients)
        msg["Message-ID"] = f"<{message_id_header}>"
        msg["Date"] = email.utils.formatdate(localtime=True)
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        # Filter out dummy/test domain recipients
        deliverable_recipients = process_recipients(recipients)

        if not deliverable_recipients:
            logger.info(f"Outbound email delivery simulated: All recipients ({recipients}) belong to test/dummy domains.")
        elif not email_settings.smtp_host or email_settings.smtp_host in ("smtp.example.com", "localhost", "dummy"):
            logger.info(f"Outbound email delivery simulated: SMTP host not configured for live delivery.")
        else:
            # Send via SMTP
            try:
                if email_settings.smtp_port == 465:
                    server = smtplib.SMTP_SSL(email_settings.smtp_host, email_settings.smtp_port, timeout=15)
                else:
                    server = smtplib.SMTP(email_settings.smtp_host, email_settings.smtp_port, timeout=15)
                    server.starttls()

                if email_settings.smtp_username and email_settings.smtp_password:
                    server.login(email_settings.smtp_username, email_settings.smtp_password)

                server.sendmail(email_settings.sender_email, deliverable_recipients, msg.as_string())
                server.quit()
                logger.info(f"Sent LG position request to {deliverable_recipients} for bank {bank.name}")

            except Exception as e:
                logger.error(f"Failed sending outbound email to {deliverable_recipients}: {e}", exc_info=True)
                raise ValueError(f"SMTP error connecting to '{email_settings.smtp_host}:{email_settings.smtp_port}'. Please verify your SMTP settings. Details: {str(e)}")

        # Record Outbound Request
        outbound_rec = InboxOutboundRequest(
            customer_id=customer_id,
            bank_id=bank_id,
            request_type="LG_POSITION",
            request_reference=req_ref,
            sent_to_emails=recipients,
            subject=subject,
            message_id=message_id_header,
            position_date=pos_date,
            sent_by_user_id=user_id,
            is_scheduled=(user_id is None)
        )
        db.add(outbound_rec)
        db.commit()
        db.refresh(outbound_rec)
        return outbound_rec

    def send_scheduled_requests(self, db: Session) -> List[InboxOutboundRequest]:
        """
        Scans active schedule configs and sends scheduled requests due today.
        Called daily by the background scheduler.
        """
        today = date.today()
        configs = db.query(InboxScheduleConfig).filter(
            InboxScheduleConfig.is_active == True,
            InboxScheduleConfig.is_deleted == False
        ).all()

        sent_requests = []
        for cfg in configs:
            is_due = False
            if cfg.frequency == "MONTHLY" and cfg.day_of_month == today.day:
                is_due = True
            elif cfg.frequency == "WEEKLY" and cfg.day_of_week == today.weekday():
                is_due = True
            elif cfg.frequency == "DAILY":
                is_due = True

            if is_due:
                try:
                    req = self.send_position_request(
                        db=db,
                        customer_id=cfg.customer_id,
                        bank_id=cfg.bank_id,
                        position_date=today,
                        custom_recipients=cfg.recipient_emails if isinstance(cfg.recipient_emails, list) else None,
                        custom_subject=cfg.custom_subject,
                        user_id=None
                    )
                    cfg.last_sent_at = datetime.now(timezone.utc)
                    sent_requests.append(req)
                except Exception as e:
                    logger.error(f"Scheduled request failed for customer {cfg.customer_id}, bank {cfg.bank_id}: {e}")

        db.commit()
        return sent_requests


inbox_outbound_service = InboxOutboundService()
