# constants.py
from enum import Enum

class UserRole(str, Enum):
    """
    Defines the roles available within the system.
    """
    SYSTEM_OWNER = "system_owner"
    CORPORATE_ADMIN = "corporate_admin"
    END_USER = "end_user"
    CHECKER = "checker"

# NEW: Defines the status of a customer's subscription.
class SubscriptionStatus(str, Enum):
    ACTIVE = "active"
    GRACE = "grace"
    EXPIRED = "expired"

class GlobalConfigKey(str, Enum):
    """
    Defines the keys for global configuration settings.
    These keys are used to identify specific configurable operational parameters.
    """
    AUTO_RENEWAL_DAYS_BEFORE_EXPIRY = "AUTO_RENEWAL_DAYS_BEFORE_EXPIRY"
    FORCED_RENEW_DAYS_BEFORE_EXPIRY = "FORCED_RENEW_DAYS_BEFORE_EXPIRY"
    AUTO_RENEW_REMINDER_START_DAYS_BEFORE_EXPIRY = "AUTO_RENEW_REMINDER_START_DAYS_BEFORE_EXPIRY"
    NUMBER_OF_DAYS_FOR_NEXT_REMINDER = "NUMBER_OF_DAYS_FOR_NEXT_REMINDER"
    REMINDER_TO_BANKS_DAYS_SINCE_DELIVERY = "REMINDER_TO_BANKS_DAYS_SINCE_DELIVERY"
    REMINDER_TO_BANKS_MAX_DAYS_SINCE_ISSUANCE = "REMINDER_TO_BANKS_MAX_DAYS_SINCE_ISSUANCE"
    MAX_DAYS_FOR_LAST_INSTRUCTION_CANCELLATION = "MAX_DAYS_FOR_LAST_INSTRUCTION_CANCELLATION"
    NUMBER_OF_DAYS_SINCE_ISSUANCE_TO_REPORT_UNDELIVERED = "NUMBER_OF_DAYS_SINCE_ISSUANCE_TO_REPORT_UNDELIVERED"
    NUMBER_OF_DAYS_SINCE_ISSUANCE_TO_STOP_REPORTING_UNDELIVERED = "NUMBER_OF_DAYS_SINCE_ISSUANCE_TO_STOP_REPORTING_UNDELIVERED"
    COMMON_COMMUNICATION_LIST = "COMMON_COMMUNICATION_LIST"
    APPROVAL_REQUEST_MAX_PENDING_DAYS = "APPROVAL_REQUEST_MAX_PENDING_DAYS"
    REMINDER_TO_BANKS_DAYS_SINCE_ISSUANCE = "REMINDER_TO_BANKS_DAYS_SINCE_ISSUANCE"
    DAYS_FOR_FIRST_PRINT_REMINDER = "DAYS_FOR_FIRST_PRINT_REMINDER"
    DAYS_FOR_PRINT_ESCALATION = "DAYS_FOR_PRINT_ESCALATION"
    RENEWAL_REMINDER_FIRST_THRESHOLD_DAYS = "RENEWAL_REMINDER_FIRST_THRESHOLD_DAYS"
    RENEWAL_REMINDER_SECOND_THRESHOLD_DAYS = "RENEWAL_REMINDER_SECOND_THRESHOLD_DAYS"
    PASSWORD_MIN_LENGTH = "PASSWORD_MIN_LENGTH"
    PASSWORD_REQUIRE_UPPERCASE = "PASSWORD_REQUIRE_UPPERCASE"
    PASSWORD_REQUIRE_LOWERCASE = "PASSWORD_REQUIRE_LOWERCASE"
    PASSWORD_REQUIRE_DIGIT = "PASSWORD_REQUIRE_DIGIT"
    PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = "PASSWORD_RESET_TOKEN_EXPIRY_MINUTES"
    # NEW: Number of days for the subscription grace period.
    GRACE_PERIOD_DAYS = "GRACE_PERIOD_DAYS"

# NEW: Defines the types of subscription-related email notifications.
class SubscriptionNotificationType(str, Enum):
    RENEWAL_REMINDER_30_DAYS = "SUBSCRIPTION_RENEWAL_REMINDER_30_DAYS"
    RENEWAL_REMINDER_7_DAYS = "SUBSCRIPTION_RENEWAL_REMINDER_7_DAYS"
    GRACE_PERIOD_START = "SUBSCRIPTION_GRACE_PERIOD_START"
    GRACE_PERIOD_END_WARNING = "SUBSCRIPTION_GRACE_PERIOD_END_WARNING"
    EXPIRED = "SUBSCRIPTION_EXPIRED"

class ApprovalRequestStatusEnum(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    AUTO_REJECTED_EXPIRED = "AUTO_REJECTED_EXPIRED"
    INVALIDATED_BY_APPROVAL = "INVALIDATED_BY_APPROVAL"
    WITHDRAWN = "WITHDRAWN"

# --- LG Action Types ---
ACTION_TYPE_LG_CREATE = "LG_CREATE"
ACTION_TYPE_LG_EXTEND = "LG_EXTENSION"
ACTION_TYPE_LG_AMEND = "LG_AMEND"
ACTION_TYPE_LG_LIQUIDATE = "LG_LIQUIDATE"
ACTION_TYPE_LG_RELEASE = "LG_RELEASE"
ACTION_TYPE_LG_DECREASE_AMOUNT = "LG_DECREASE_AMOUNT"
ACTION_TYPE_LG_ACTIVATE_NON_OPERATIVE = "LG_ACTIVATE_NON_OPERATIVE"
ACTION_TYPE_LG_CANCEL_LAST_INSTRUCTION = "LG_CANCEL_LAST_INSTRUCTION"
DOCUMENT_TYPE_ORIGINAL_LG = "ORIGINAL_LG_DOCUMENT"
ACTION_TYPE_LG_RECORD_DELIVERY = "LG_RECORD_DELIVERY"
ACTION_TYPE_LG_RECORD_BANK_REPLY = "LG_RECORD_BANK_REPLY"
ACTION_TYPE_LG_REMINDER_TO_BANKS = "LG_REMINDER_TO_BANKS"
ACTION_TYPE_LG_BULK_REMINDER_TO_BANKS = "LG_BULK_REMINDER_TO_BANKS"
ACTION_TYPE_LG_REMINDER_TO_INTERNAL_OWNER = "LG_REMINDER_TO_INTERNAL_OWNER"
ACTION_TYPE_LG_RUN_AUTO_RENEWAL = "LG_RUN_AUTO_RENEWAL"
ACTION_TYPE_LG_RUN_BULK_RENEWAL = "LG_BULK_RENEWAL"
ACTION_TYPE_LG_UNDELIVERED_INSTRUCTIONS_REPORT = "LG_UNDELIVERED_INSTRUCTIONS_REPORT"
ACTION_TYPE_INTERNAL_OWNER_CHANGE = "INTERNAL_OWNER_CHANGE"
ACTION_TYPE_LG_CHANGE_OWNER_DETAILS = "LG_CHANGE_OWNER_DETAILS"
ACTION_TYPE_LG_CHANGE_SINGLE_LG_OWNER = "LG_CHANGE_SINGLE_LG_OWNER"
ACTION_TYPE_LG_CHANGE_BULK_LG_OWNER = "LG_CHANGE_BULK_LG_OWNER"
ACTION_TYPE_LG_TOGGLE_AUTO_RENEWAL = "LG_TOGGLE_AUTO_RENEWAL"
ACTION_TYPE_LG_RENEWAL_REMINDER_FIRST = "LG_RENEWAL_REMINDER_FIRST"
ACTION_TYPE_LG_RENEWAL_REMINDER_SECOND = "LG_RENEWAL_REMINDER_SECOND"
ACTION_TYPE_LG_CANCEL_LAST_INSTRUCTION = "LG_CANCEL_LAST_INSTRUCTION"


# List of action types that require approval (Maker-Checker workflow)
ACTION_TYPES_REQUIRING_APPROVAL = [
    ACTION_TYPE_LG_RELEASE,
    ACTION_TYPE_LG_LIQUIDATE,
    ACTION_TYPE_LG_DECREASE_AMOUNT,
    ACTION_TYPE_LG_CHANGE_OWNER_DETAILS,
    ACTION_TYPE_LG_CHANGE_SINGLE_LG_OWNER,
    ACTION_TYPE_LG_CHANGE_BULK_LG_OWNER,
    ACTION_TYPE_LG_AMEND,
    ACTION_TYPE_LG_ACTIVATE_NON_OPERATIVE,
    ACTION_TYPE_LG_CANCEL_LAST_INSTRUCTION
]

# --- NEW: Instruction Type Codes (for new serial format) ---
# These are the 2-character codes used in the instruction serial number
class InstructionTypeCode(str, Enum):
    EXT = "EX" # Extension
    REL = "RL" # Release
    LIQ = "LQ" # Liquidation
    DEC = "DC" # Decrease Amount
    AMD = "AM" # Amendment
    ACT = "AC" # Activate Non-Operative
    DEL = "DL" # Record Delivery
    RPL = "RP" # Record Bank Reply
    REM = "RM" # Reminder to Banks
    CNC = "CN" # Cancel Last Instruction

# --- NEW: Sub-Instruction Type Codes (for new serial format) ---
# These are the 1-character codes used as the suffix in the instruction serial number
class SubInstructionCode(str, Enum):
    ORIGINAL = "O" # Original instruction (e.g., generated for Extension, Release, etc.)
    DELIVERY_PROOF = "D" # Associated with recording delivery of an instruction
    BANK_REPLY = "R" # Associated with recording a bank's reply to an instruction
    BANK_REMINDER = "M" # Associated with sending a reminder to the bank

# --- NEW: Map from Instruction Type Code to Full Action Type String ---
# This is crucial for retrieving the full action type from the short code in the serial.
INSTRUCTION_TYPE_CODE_TO_FULL_ACTION_MAP = {
    InstructionTypeCode.EXT: ACTION_TYPE_LG_EXTEND,
    InstructionTypeCode.REL: ACTION_TYPE_LG_RELEASE,
    InstructionTypeCode.LIQ: ACTION_TYPE_LG_LIQUIDATE,
    InstructionTypeCode.DEC: ACTION_TYPE_LG_DECREASE_AMOUNT,
    InstructionTypeCode.AMD: ACTION_TYPE_LG_AMEND,
    InstructionTypeCode.ACT: ACTION_TYPE_LG_ACTIVATE_NON_OPERATIVE,
    InstructionTypeCode.REM: ACTION_TYPE_LG_REMINDER_TO_BANKS,
    InstructionTypeCode.CNC: ACTION_TYPE_LG_CANCEL_LAST_INSTRUCTION,
}

# --- LG Category Codes (for new serial format) ---
# This is NOT an enum, but a list of common LG Category Codes to be used in the serial.
# Should correspond to codes in LGCategory and UniversalCategory models.
# Example: AP for Advance Payment, PB for Performance Bond, etc.
# The actual value used will come from the LGRecord.lg_category.code.

# --- Audit Log Action Types (specific to audit logs for clarity, if distinct from general actions) ---
AUDIT_ACTION_TYPE_CREATE = "CREATE"
AUDIT_ACTION_TYPE_UPDATE = "UPDATE"
AUDIT_ACTION_TYPE_DELETE = "DELETE"
AUDIT_ACTION_TYPE_SOFT_DELETE = "SOFT_DELETE"
AUDIT_ACTION_TYPE_RESTORE = "RESTORE"
AUDIT_ACTION_TYPE_LOGIN_SUCCESS = "LOGIN_SUCCESS"
AUDIT_ACTION_TYPE_LOGIN_FAILED = "LOGIN_FAILED"
AUDIT_ACTION_TYPE_LOGOUT = "LOGOUT"
AUDIT_ACTION_TYPE_CUSTOMER_ONBOARD = "CUSTOMER_ONBOARD"
AUDIT_ACTION_TYPE_PASSWORD_CHANGE_FIRST_LOGIN_SUCCESS = "PASSWORD_CHANGE_FIRST_LOGIN_SUCCESS"
AUDIT_ACTION_TYPE_PASSWORD_CHANGE_FIRST_LOGIN_FAILED = "PASSWORD_CHANGE_FIRST_LOGIN_FAILED"
AUDIT_ACTION_TYPE_AI_SCAN_SUCCESS = "AI_SCAN_SUCCESS"
AUDIT_ACTION_TYPE_AI_SCAN_FAILED = "AI_SCAN_FAILED"
AUDIT_ACTION_TYPE_NOTIFICATION_SENT = "NOTIFICATION_SENT"
AUDIT_ACTION_TYPE_NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
AUDIT_ACTION_TYPE_INSTRUCTION_ACCESSED_FOR_PRINT = "INSTRUCTION_ACCESSED_FOR_PRINT"

# Approval-specific Audit Actions
AUDIT_ACTION_TYPE_APPROVAL_REQUEST_SUBMITTED = "APPROVAL_REQUEST_SUBMITTED"
AUDIT_ACTION_TYPE_APPROVAL_REQUEST_APPROVED = "APPROVAL_REQUEST_APPROVED"
AUDIT_ACTION_TYPE_APPROVAL_REQUEST_REJECTED = "APPROVAL_REQUEST_REJECTED"
AUDIT_ACTION_TYPE_APPROVAL_REQUEST_WITHDRAWN = "APPROVAL_REQUEST_WITHDRAWN"
AUDIT_ACTION_TYPE_APPROVAL_REQUEST_AUTO_REJECTED = "APPROVAL_REQUEST_AUTO_REJECTED"
AUDIT_ACTION_TYPE_APPROVAL_INVALIDATED_BY_OTHER_APPROVAL = "APPROVAL_INVALIDATED_BY_OTHER_APPROVAL"
AUDIT_ACTION_TYPE_APPROVAL_LG_STATE_CHANGED = "APPROVAL_LG_STATE_CHANGED"
AUDIT_ACTION_TYPE_APPROVAL_INVALIDATED_LG_MISSING = "APPROVAL_INVALIDATED_LG_MISSING"
AUDIT_ACTION_TYPE_APPROVAL_REJECTED_SELF_APPROVAL = "APPROVAL_REJECTED_SELF_APPROVAL"
AUDIT_ACTION_TYPE_APPROVAL_INVALIDATED_ENTITY_MISSING = "APPROVAL_INVALIDATED_ENTITY_MISSING"
AUDIT_ACTION_TYPE_APPROVAL_ENTITY_STATE_CHANGED = "APPROVAL_ENTITY_STATE_CHANGED"

# LG Transactional Audit Actions
AUDIT_ACTION_TYPE_LG_EXTENDED = "LG_EXTENDED"
AUDIT_ACTION_TYPE_LG_RELEASED = "LG_RELEASED"
AUDIT_ACTION_TYPE_LG_LIQUIDATED_FULL = "LG_LIQUIDATED_FULL"
AUDIT_ACTION_TYPE_LG_LIQUIDATED_PARTIAL = "LG_LIQUIDATED_PARTIAL"
AUDIT_ACTION_TYPE_LG_DECREASED_AMOUNT = "LG_DECREASED_AMOUNT"
AUDIT_ACTION_TYPE_LG_AMENDED = "LG_AMENDED"
AUDIT_ACTION_TYPE_LG_ACTIVATED = "LG_ACTIVATED"
AUDIT_ACTION_TYPE_LG_AUTO_RENEWAL_TOGGLED = "LG_AUTO_RENEWAL_TOGGLED"

# Audit Actions for Internal Owner Change
AUDIT_ACTION_TYPE_LG_OWNER_DETAILS_UPDATED = "LG_OWNER_DETAILS_UPDATED"
AUDIT_ACTION_TYPE_LG_SINGLE_OWNER_CHANGED = "LG_SINGLE_OWNER_CHANGED"
AUDIT_ACTION_TYPE_LG_BULK_OWNER_CHANGED = "LG_BULK_OWNER_CHANGED"

# NEW Audit Actions for Instruction Delivery/Reply and Reminders
AUDIT_ACTION_TYPE_LG_INSTRUCTION_DELIVERED = "LG_INSTRUCTION_DELIVERED"
AUDIT_ACTION_TYPE_LG_BANK_REPLY_RECORDED = "LG_BANK_REPLY_RECORDED"
AUDIT_ACTION_TYPE_LG_REMINDER_SENT_TO_BANK = "LG_REMINDER_TO_BANKS"
AUDIT_ACTION_TYPE_LG_BULK_REMINDER_INITIATED = "LG_BULK_REMINDER_INITIATED"
AUDIT_ACTION_TYPE_LG_REMINDER_SENT_TO_INTERNAL_OWNER = "LG_REMINDER_TO_INTERNAL_OWNER"
AUDIT_ACTION_TYPE_LG_UNDELIVERED_INSTRUCTIONS_REPORT_SENT = "LG_UNDELIVERED_INSTRUCTIONS_REPORT_SENT"

# NEW: Audit actions for print reminders and escalation
AUDIT_ACTION_TYPE_PRINT_REMINDER_SENT = "PRINT_REMINDER_SENT"
AUDIT_ACTION_TYPE_PRINT_ESCALATION_SENT = "PRINT_ESCALATION_SENT"

# NEW: Action Type for the email confirming transaction completeness after printing.
NOTIFICATION_PRINT_CONFIRMATION = "NOTIFICATION_PRINT_CONFIRMATION"

# NEW: Audit actions for new renewal reminders
AUDIT_ACTION_TYPE_LG_RENEWAL_REMINDER_FIRST_SENT = "LG_RENEWAL_REMINDER_FIRST_SENT"
AUDIT_ACTION_TYPE_LG_RENEWAL_REMINDER_SECOND_SENT = "LG_RENEWAL_REMINDER_SECOND_SENT"
AUDIT_ACTION_TYPE_LG_OWNER_RENEWAL_REMINDER_SENT = "LG_OWNER_RENEWAL_REMINDER_SENT"
AUDIT_ACTION_TYPE_LG_OWNER_RENEWAL_REMINDER_SKIPPED_RECENTLY_SENT = "LG_OWNER_RENEWAL_REMINDER_SKIPPED_RECENTLY_SENT"

# NEW AUTH_V2 Audit Actions
AUDIT_ACTION_TYPE_PASSWORD_RESET_INITIATED = "PASSWORD_RESET_INITIATED"
AUDIT_ACTION_TYPE_PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"
AUDIT_ACTION_TYPE_PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"
AUDIT_ACTION_TYPE_ADMIN_PASSWORD_SET = "ADMIN_PASSWORD_SET"
AUDIT_ACTION_TYPE_ADMIN_PASSWORD_RESET = "ADMIN_PASSWORD_RESET"

# NEW Audit actions for instruction cancellation
AUDIT_ACTION_TYPE_LG_INSTRUCTION_CANCELED = "LG_INSTRUCTION_CANCELED"
AUDIT_ACTION_TYPE_LG_INSTRUCTION_CANCELLATION_FAILED = "LG_INSTRUCTION_CANCELLATION_FAILED"

# --- LG Status IDs (MUST match the actual INTEGER IDs in your lg_statuses table) ---
class LgStatusEnum(int, Enum): # Base class changed to int
    VALID = 1
    RELEASED = 2
    LIQUIDATED = 3
    EXPIRED = 4

class LgOperationalStatusEnum(int, Enum):
    OPERATIVE = 1
    NON_OPERATIVE = 2

# --- LG Type IDs (MUST match the actual INTEGER IDs in your lg_types table) ---
class LgTypeEnum(int, Enum):
    PERFORMANCE_GUARANTEE = 1
    BID_BOND = 2
    ADVANCE_PAYMENT_GUARANTEE = 3
    FINANCIAL_GUARANTEE = 4